# Exercício de Programação 5

<font color="red">**Prazo de submissão: 23:55 do dia 23.08.2021** </font>

2021.1 Álgebra Linear Computacional - DCC - UFMG

Erickson - Fabricio

Instruções:
* Antes de submeter suas soluções, certifique-se de que tudo roda como esperado. Primeiro, **reinicie o kernel** no menu, selecione Kernel$\rightarrow$Restart e então execute **todas as células** (no menu, Cell$\rightarrow$Run All)
* Apenas o arquivo .ipynb deve ser submetido. Ele não deve ser compactado.
* Não deixe de preencher seu nome e número de matrícula na célula a seguir

**Nome do aluno:** VINICIUS TRINDADE DIAS ABEL

**Matricula:** 2020007112

## Introdução
Esse EP será dividido em 2 partes:

1. Métodos iterativos para calcular autovalores e singular values.
3. Métodos iterativos para solução de sistemas $Ax = b$ (Jacob e Seidel)

Os conceitos cobrados aqui são discutidos nas aulas que abrangem o conteúdo de cada parte e elas devem ser a principal fonte de consulta para suas soluções.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

### Questão 1 - Cálculo de autovalores e valores singulares


Nessa primeira parte, vamos implementar o algoritmo QR para obtenção dos autovalores de uma matriz A, como foi descrito nas aulas.

Abaixo temos a matriz A:

In [ ]:
# ATENÇÃO: Não editar esta célula
A = np.vander(np.array([5, 4, 3, 2, 1]))
print(A)

[[625 125  25   5   1]
 [256  64  16   4   1]
 [ 81  27   9   3   1]
 [ 16   8   4   2   1]
 [  1   1   1   1   1]]


**1.1.1** Implemente o algoritmo QR, utilizando um **while loop** até satisfazer a condição: $A_i[1][0] < 10^{-10}$. Para tanto, lembre-se dos passos do algoritmo discutidos em aula:

Inicializando:
$A_0 = A$ \\
Em cada loop: \\
$A_0 = Q_0R_0$ \\
$A_1 = Q_0^T A_0 Q_0$ \\
$A_0 \leftarrow A_1$ \\


Para a decomposição QR, utilize o comando [`np.linalg.qr`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html).

Ao final do loop imprima os resultados: \\

print(iter, A[1][0], A)

iter = número de iterações necessárias para convergência.

In [ ]:
# Insira seu código aqui

**1.1.2** Repita o exercício anterior, agora simplificando o algoritmo QR, considerando a relação:

$$Q_0^TA_0 = R_0$$

Ao final do loop imprima os resultados: \\

print(iter, R_0, A[1][0], A)

iter = número de iterações necessárias para convergência.

In [ ]:
# Insira seu código aqui

O próximo passo agora é utilizar o algoritmo QR para encontrar valores singulares de matrizes não quadradas. Considere para este exercício as matrizes B e C abaixo:

In [ ]:
B = np.array([[4, 5, 6], [7, 8, 9]])
C = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [10, 10, 7, 2]])
print('B:', '\n', B)
print('C:', '\n', C)

B: 
 [[4 5 6]
 [7 8 9]]
C: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 10  7  2]]


**1.2.1** Para resolver essa questão, lembre-se que para qualquer matriz não quadrada B:

1. Existe uma decomposição $B = U \Sigma V^T$ 

1. $B^T B$ é quadrada, simétrica e admite decomposição espectral da forma: $B^T B = Q \Lambda Q^T$

3. Substituindo 1 em 2, temos: $B^T B = V \Sigma^2 V^T$

A nível de algoritmo, crie uma função generalista que retorna os valores singulares de qualquer matriz real, não quadrada seguindo os passos:

1. Calcule $S =B^T B$
2. Use o algoritmo QR para obter autovalores de $S$ (loop com 10 iterações).
3. Tire a raiz quadrada dos autovalores de S para obter os valores singulares de B.
4. Retorne um vetor **apenas com os valores singulares não nulos** (dica: [`np.diag`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)).

Imprima a saída da sua função para B e C.

In [ ]:
# Insira seu código aqui

### Questão 2 -Gauss-Jacobi e Gauss Seidel

Nesta seçãoo, vamos implementar os algoritmos de Gauss-Jacobi e Gauss Seidel para resolver o sistema $Ax = b$, tal como foi descrito nas aulas.

Dica 1:

Passos iterativos do método Gauss-Jacobi para uma matriz 3x3:

Dado um valor inicial para x: $\vec{x}^{k = 0} = [1, 1, 1]$

Realize a iteração:

$x_1^{k+1} = (b_1 - a_{12} x_2^{(k)} - a_{13}x_3^{(k)})/a_{11}$

$x_2^{k+1} = (b_2 - a_{21} x_1^{(k)} - a_{23}x_3^{(k)})/a_{22}$

$x_3^{k+1} = (b_3 - a_{31} x_1^{(k)} - a_{32}x_2^{(k)})/a_{33}$

Dica 2:

Passos iterativos do método Gauss-Seidel para uma matriz 3x3:

Dado um valor inicial para x: $\vec{x}^{k = 0} = [1, 1, 1]$

Realize a iteração:

$x_1^{k+1} = (b_1 - a_{12} x_2^{(k)} - a_{13}x_3^{(k)})/a_{11}$

$x_2^{k+1} = (b_2 - a_{21} x_1^{(k+1)} - a_{23}x_3^{(k)})/a_{22}$

$x_3^{k+1} = (b_3 - a_{31} x_1^{(k+1)} - a_{32}x_2^{(k+1)})/a_{33}$

Dica 3:

Ao fazer o exercício no Colab tive problemas de arredondamento ao criar o vetor x_iter com o comando np.array. Caso tenham este problema, basta declarar x_iter como uma lista.

**2.1** Encontre a solução do sistema $Ax = b$, pelo método de Gauss-Jacobi realizando a iteração do método 5 vezes. A cada iteração, realize o print da sua estimativa para x. Neste exercício, considere a primeira estimativa de $x = [1, 1, 1]$, com A e b definidos abaixo.

Após rodar o algoritmo, faça um print da sua solução, comparando com a saída do método numpy: np.linalg.solve(A,b)

In [ ]:
# ATENÇÃO: Não editar esta célula
A = np.array([[27, 6, -2], [6, 15, 2], [1, 1, 54]])
b = np.array([85, 72, 110])
print('A: \n', A)
print('b: \n', b)

A: 
 [[27  6 -2]
 [ 6 15  2]
 [ 1  1 54]]
b: 
 [ 85  72 110]


In [ ]:
# Insira seu código aqui

**2.2** Repita o exercício anterior, agora pelo método de Gauss-Seidel

In [ ]:
# Insira seu código aqui